Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -226,7 +226,8 @@ jobs:
             echo "No API instance ID found, skipping policy application."
           else
             echo "Applying Client ID Enforcement policy to API instance $API_INSTANCE_ID..."
-            anypoint-cli-v4 api-mgr:policy:apply "$API_INSTANCE_ID" --groupId 68ef9520-24e9-4cf2-b2f5-620025690913 --assetId client-id-enforcement --assetVersion 1.3.2 --config '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}' || echo "Policy apply failed or already applied."
+            LATEST_POLICY_VERSION=$(anypoint-cli-v4 exchange:asset:list --groupId 68ef9520-24e9-4cf2-b2f5-620025690913 --assetId client-id-enforcement --output json | jq -r '.[0].version')
+            anypoint-cli-v4 api-mgr:policy:apply "$API_INSTANCE_ID" client-id-enforcement --policyVersion "$LATEST_POLICY_VERSION" --config '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}' || echo "Policy apply failed or already applied."
           fi
 
 
@@ -321,8 +322,9 @@ jobs:
           mvn -B mule:deploy -s .maven/settings.xml -DmuleDeploy -Danypoint.organization=${{ secrets.ORG_ID }} -Denv=${{ env.TARGET_ENV }} -Dapplication.version=$PREVIOUS_VERSION -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" -Dnexus.username="${{ secrets.NEXUS_USERNAME }}" -Dnexus.password="${{ secrets.NEXUS_PASSWORD }}" -Dapp.name="${APP_NAME}"
 
           if [ -n "$API_INSTANCE_ID" ]; then
-            echo "Re-applying Client ID Enforcement policy..."
-            anypoint-cli-v4 api-mgr:policy:apply "$API_INSTANCE_ID" client-id-enforcement --config '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}' || echo "Policy re-apply failed or already present."
+            LATEST_POLICY_VERSION=$(anypoint-cli-v4 exchange:asset:list --groupId 68ef9520-24e9-4cf2-b2f5-620025690913 --assetId client-id-enforcement --output json | jq -r '.[0].version')
+            echo "Re-applying Client ID Enforcement policy version $LATEST_POLICY_VERSION..."
+            anypoint-cli-v4 api-mgr:policy:apply "$API_INSTANCE_ID" client-id-enforcement --policyVersion "$LATEST_POLICY_VERSION" --config '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}' || echo "Policy re-apply failed or already present."
           else
             echo "No API instance id found, skipping policy reapply."
           fi
