Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -226,7 +226,7 @@ jobs:
             echo "No API instance ID found, skipping policy application."
           else
             echo "Applying Client ID Enforcement policy to API instance $API_INSTANCE_ID..."
-            anypoint-cli-v4 api-mgr:policy:apply "$API_INSTANCE_ID" client-id-enforcement --config '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}' || echo "Policy apply failed or already applied."
+            anypoint-cli-v4 api-mgr:policy:apply "$API_INSTANCE_ID" --groupId 68ef9520-24e9-4cf2-b2f5-620025690913 --assetId client-id-enforcement --assetVersion 1.3.2 --config '{"credentialsOrigin":"HTTP_BASIC_AUTHORIZATION_HEADER"}' || echo "Policy apply failed or already applied."
           fi
 
 
